### ISSUE TITLE
PS4 5.05 KERNEL OFFSETS

### ISSUE THREAD

**Issue by MegiasHack** [BISOON/GTA5-Native-Caller#2]
I have implemented 5.05 kernel offsets but the tool only connect and not attach never.

**Comment by 0xwal** [comment]
Yes this seems API problem, I will try to fix it soon, and the GTANative could be used with different PS4 API, only need (read/write) function..

**Comment by MegiasHack** [comment]
Ok, Thanks.

**Comment by 0xwal** [comment]
Ok works for 5.05, use this [PS4API.BIN](https://github.com/BISOON/PS4-API-SERVER/blob/temp-5.05/ps4-api-server_5.05.bin)
